// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBix1jVcYYRCpxcR34X1p8dn8lXRjjCvWU',
    appId: '1:673842473312:web:a78dc42a73ac6ca5f15605',
    messagingSenderId: '673842473312',
    projectId: 'jim-carrier',
    authDomain: 'jim-carrier.firebaseapp.com',
    storageBucket: 'jim-carrier.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyV2PnlDt3cBbW_v_8yWqIkGc6zYFebFg',
    appId: '1:673842473312:android:e99ef762b6d1c323f15605',
    messagingSenderId: '673842473312',
    projectId: 'jim-carrier',
    storageBucket: 'jim-carrier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJnIc2AW9rS76XM01HmuE2wn1aMu4NjVs',
    appId: '1:673842473312:ios:f458e90ec33ee931f15605',
    messagingSenderId: '673842473312',
    projectId: 'jim-carrier',
    storageBucket: 'jim-carrier.firebasestorage.app',
    iosClientId:
        '673842473312-a6aiqmrt9f32urlts7hivun8ckthjsgf.apps.googleusercontent.com',
    iosBundleId: 'jim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJnIc2AW9rS76XM01HmuE2wn1aMu4NjVs',
    appId: '1:673842473312:ios:5c8847f350b12a09f15605',
    messagingSenderId: '673842473312',
    projectId: 'jim-carrier',
    storageBucket: 'jim-carrier.firebasestorage.app',
    iosClientId:
        '673842473312-or46efk6nr98iqeqrugo2u6bkg06lbc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.jim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBix1jVcYYRCpxcR34X1p8dn8lXRjjCvWU',
    appId: '1:673842473312:web:edcbd13f822eec07f15605',
    messagingSenderId: '673842473312',
    projectId: 'jim-carrier',
    authDomain: 'jim-carrier.firebaseapp.com',
    storageBucket: 'jim-carrier.firebasestorage.app',
  );
}
